project_name: khinsider
builds:
  - binary: khinsider
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
release:
  github:
    owner: marcus-crane
    name: khinsider
  prerelease: auto
brews:
  - tap:
      owner: marcus-crane
      name: homebrew-tap
      branch: main
    commit_author:
      name: utf9k Release Bot
      email: helper@utf9k.net
    commit_msg_template: "Brew formula updater for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://utf9k.net"
    description: "easily fetch videogame soundtracks from downloads.khinsider.com"
    license: "MIT"
    skip_upload: auto
