name: "Update khinsider index"
on:
  schedule:
  - cron: "0 * * * *"

jobs:
  index-sync:
    name: index-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - run: go mod download
      - run: go run main.go index
      - run: cp /home/runner/.khinsider/index.json .
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/marcus-crane/7b27c3b2772115ce7dbb7be792a7ad75
          gist_title: index.json
          github_file: index.json
